extends Resource
class_name SlimeTuning

@export var scoot_distance := 5.0
@export var scoot_duration := 0.34
@export var attack_frame_time := 0.08
@export var attack_hit_frame := 5
@export var attack_range := 14.0
@export var attack_hit_range := 16.0
@export var attack_vertical_hit_range := 10.0
@export var aggro_range := 28.0
@export var attack_cooldown := 1.0
@export var attack_lunge_distance := 10.0
@export var boss_attack_cooldown_multiplier := 1.6
@export var boss_attack_frame_time_multiplier := 1.5
@export var boss_movement_speed_multiplier := 0.7
@export var hold_min := 0.22
@export var hold_max := 0.48
@export var aggro_hold_min := 0.08
@export var aggro_hold_max := 0.16
@export var chill_chance := 0.22
@export var chill_min := 1.0
@export var chill_max := 2.2
@export var idle_breath_time := 1.4
@export var repath_min := 0.7
@export var repath_max := 1.8
@export var steering_direction_count := 8
@export var steering_approach_weight := 1.0
@export var steering_orbit_weight := 0.42
@export var steering_ally_danger_weight := 1.25
@export var steering_blocked_danger_weight := 4.0
@export var steering_clearance := 7.0
@export var regen_delay := 5.0
@export var regen_interval := 0.75
@export var regen_amount := 1.0
@export var health_drain_fill_speed := 80.0
@export var health_regen_fill_speed := 4.0
@export var health_damage_hang_time := 0.14
@export var hit_flash_time := 0.12
@export var hitstun_time := 1.0 / 30.0
@export var knockback_duration := 0.14
@export var ambush_reveal_window := 0.5
@export var ambush_block_stun := 1.0
@export var ambush_hit_extension := 0.5
