[CmdletBinding()]
param(
    [string]$ProjectRoot = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = Split-Path -Parent $PSScriptRoot
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $ProjectRoot "docs/SCRIPT_INDEX.md"
}

$scriptRoot = Join-Path $ProjectRoot "scripts"
$files = Get-ChildItem -LiteralPath $scriptRoot -Filter "*.gd" -File | Sort-Object FullName
$rows = [System.Collections.Generic.List[string]]::new()
$rows.Add("# Tiny Demons Script Index")
$rows.Add("")
$rows.Add("Generated by ``tools/generate_script_index.ps1``. Refresh after adding, moving, or materially splitting a script.")
$rows.Add("")
$rows.Add("This is a navigation index, not an ownership replacement. Start with ``docs/FEATURE_MAP.md`` for feature ownership and ``docs/ARCHITECTURE.md`` for boundaries.")
$rows.Add("")
$rows.Add("| Script | Lines | Class / base | Signals | Exports | Functions |")
$rows.Add("|---|---:|---|---:|---:|---|")

foreach ($file in $files) {
    $relative = $file.FullName.Substring($ProjectRoot.Length + 1).Replace('\', '/')
    $lines = @(Get-Content -LiteralPath $file.FullName)
    $classMatch = $lines | Select-String -Pattern '^class_name\s+([^\s]+)' | Select-Object -First 1
    $baseMatch = $lines | Select-String -Pattern '^extends\s+(.+)$' | Select-Object -First 1
    $class = if ($null -eq $classMatch) { "-" } else { $classMatch.Matches[0].Groups[1].Value }
    $base = if ($null -eq $baseMatch) { "-" } else { $baseMatch.Matches[0].Groups[1].Value.Trim() }
    $signals = @($lines | Select-String -Pattern '^signal\s+' ).Count
    $exports = @($lines | Select-String -Pattern '^@export' ).Count
    $functions = [System.Collections.Generic.List[string]]::new()
    foreach ($match in ($lines | Select-String -Pattern '^\s*(?:static\s+)?func\s+([A-Za-z0-9_]+)\s*\(')) {
        $name = $match.Matches[0].Groups[1].Value
        $functions.Add("[$name](../${relative}:$($match.LineNumber))")
    }
    $functionText = if ($functions.Count -eq 0) { "-" } else { ($functions -join ", ") }
    $display = "[$relative](../$relative)"
    if ($lines.Count -ge 1000) { $display += " [large]" }
    $rows.Add("| $display | $($lines.Count) | ``$class`` / ``$base`` | $signals | $exports | $functionText |")
}

$rows.Add("")
$rows.Add("## Navigation notes")
$rows.Add("")
$rows.Add("- [large] marks a script at or above 1,000 lines; size alone is not a refactor instruction.")
$rows.Add("- Function links point to the declaration line in the current checkout.")
$rows.Add("- Generated indexes should be refreshed in the same change as script moves so links remain useful.")

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllLines($OutputPath, $rows)
Write-Output "Wrote $OutputPath ($($files.Count) scripts)."
