extends Node2D
class_name GameplayState

const SLIME_ATTACK_FRAME_SIZE := Vector2i(16, 16)
const EDGE_MARGIN := 0.35
const SLIME_EDGE_PADDING := 0.0
const ACTOR_FOOT_OFFSET := Vector2(8, 15)
const DEPTH_Z_SCALE := 10.0
const OVERWORLD_UI_Z := 4090
const VERTICAL_MOVEMENT_SCALE := 0.5
const MAX_ACTIVE_ENEMY_ATTACKERS := 2
const PLAYER_FRAME_SIZE := Vector2i(36, 36)
const PLAYER_ATTACK_FRAME_SIZE := Vector2i(36, 36)
const ROLL_DUST_FRAME_SIZE := Vector2i(16, 16)
const GAME_OVER_FADE_TIME := 0.8
const PLAYER_TEXTURE_OFFSET := Vector2(-10, -10)
const CHEST_INTERACT_DISTANCE := 16.0
const NPC_INTERACT_DISTANCE := 24.0
const CHEST_REWARD_GOLD := 100
const INTERACT_PROMPT_BOB_TIME := 0.8
const CHEST_COLLECT_FLASH_TIME := 0.12
const CHEST_UNLOCK_FADE_TIME := 0.45
const CHEST_EVAPORATE_PARTICLE_COUNT := 34
const CHEST_EVAPORATE_LIFETIME_MIN := 0.45
const CHEST_EVAPORATE_LIFETIME_MAX := 0.9
const FIRE_FRAME_TIME := 0.16
const FIRE_FRAME_SIZE := Vector2i(16, 16)
const CLOAKED_DEMON_FRAME_SIZE := Vector2i(36, 36)
const NPC_DIALOGUE_TIME := 3.2
const NPC_DIALOGUE_BUTTON_BOB_TIME := 1.6
const PLAYER_DOOR_FOOT_COLLIDER_SIZE := Vector2(3, 3)
const ACTOR_COLLISION_WIDTH := 9.0
const ACTOR_COLLISION_HEIGHT := 4.0
const ACTOR_CONTACT_RADIUS := 3.6
const CHEST_COLLISION_SIZE := Vector2(11, 6)
const SLIME_WEIGHT := 1.45
const PLAYER_WEIGHT := 1.0
const TARGET_LOCK_MAX_DISTANCE := 9999.0
const OCCLUSION_RELEASE_GRACE := 0.08
const CONTROLLER_DEADZONE := 0.25
const CONTROLLER_TRIGGER_DEADZONE := 0.35
const OCCLUDER_PATHS: Array[NodePath] = [
	^"Actors/Chest",
]
@onready var floor_tiles: Node2D = $Map/FloorTiles
@onready var ui: Node2D = $UI
@onready var player: Sprite2D = $Actors/TinyDemon
@onready var player_attack_visual: Sprite2D = $Actors/TinyDemonAttack
@onready var player_shadow: Sprite2D = $Actors/TinyDemonShadow
@onready var cloaked_demon_shadow: Sprite2D = $Actors/CloakedDemonShadow
@onready var slime_blue: Sprite2D = $Actors/SlimeBlue
@onready var slime_green: Sprite2D = $Actors/SlimeGreen
@onready var slime_red: Sprite2D = $Actors/SlimeRed
@onready var sockets_root: Node2D = $Map/Sockets
@onready var hp_overhead: Sprite2D = $Actors/SlimeGreen/HpOverhead
@onready var hp_overhead_fill: Sprite2D = $Actors/SlimeGreen/HpOverheadFill
@onready var chest: Sprite2D = $Actors/Chest
@onready var rest_fire: Sprite2D = $Actors/RestFire
@onready var rest_fire_depth_marker: Marker2D = $Actors/RestFire/DepthMarker
@onready var cloaked_demon: Sprite2D = $Actors/CloakedDemon
@onready var cloaked_demon_depth_marker: Marker2D = $Actors/CloakedDemon/DepthMarker
@onready var target_name_text: Sprite2D = $UI/SlimeText
@onready var target_health_bar: Sprite2D = $UI/EnemyHp
@onready var target_health_fill: Sprite2D = $UI/EnemyHpFill
@onready var player_health_fill: Sprite2D = $UI/HpBarFill
@onready var player_stats: StatsComponent = $Actors/TinyDemon/Stats
var player_equipment: EquipmentComponent = null
var player_health_component: HealthComponent = null
var player_motor: ActorMotor = null
var player_controller: PlayerController = null
var player_roll_component: PlayerRollComponent = null
var player_attack_component: PlayerAttackComponent = null
var player_animation_component: PlayerAnimationComponent = null
var player_equipment_visual_component: PlayerEquipmentVisualComponent = null
var walkable_area: WalkableArea = null
var actor_collision_system: ActorCollisionSystem = null
var depth_sorter: DepthSorter = null
var occlusion_renderer: OcclusionRenderer = null
var room_controller: RoomController = null
var shadow_controller: ShadowController = null
var interaction_component: InteractionComponent = null
var chest_controller: ChestController = null
var npc_controller: NpcController = null
var rest_fire_controller: RestFireController = null
var hud_controller: HudController = null
var effects_spawner: EffectsSpawner = null
var screen_state_controller: ScreenStateController = null
var gameplay_frame_controller: GameplayFrameController = null
var player_idle_frames: Array[Texture2D] = []
var player_walk_frames: Array[Texture2D] = []
var player_attack_frames: Array[Texture2D] = []
var player_attack2_frames: Array[Texture2D] = []
var player_attack_left_frames: Array[Texture2D] = []
var player_attack2_left_frames: Array[Texture2D] = []
var slime_attack_frames_by_palette: Dictionary = {}
var player_between_attack_texture: Texture2D = null
var player_after_attack2_texture: Texture2D = null
var player_just_finished_attack2 := false
var player_between_timer := 0.0
var player_anim_name := "idle"
var player_anim_frame := 0
var player_anim_timer := 0.0
var player_is_moving := false
var player_is_attacking := false
var player_is_rolling := false
var player_roll_frames: Array[Texture2D] = []
var roll_dust_spawned_this_roll := false
var player_roll_input_was_down := false
var roll_dust_frames: Array[Texture2D] = []
var roll_dust_flipped_frames: Array[Texture2D] = []
var player_attack_input_was_down := false
var player_attack_hit_done := false
var player_attack_hit_targets: Array[Sprite2D] = []
var player_attack_flip_h := false
var player_hit_flash_timer := 0.0
var player_hitstun_timer := 0.0
var walkable_points: Array[Vector2] = []
var walkable_polygons: Array[PackedVector2Array] = []
var walkable_outline: PackedVector2Array = PackedVector2Array()
var entrance_block_polygons: Array[PackedVector2Array] = []
var use_walkable_polygon_direct := false
var slimes: Array[Sprite2D] = []
var depth_sprites: Array[Sprite2D] = []
var actor_sprites: Array[Sprite2D] = []
var collision_sprites: Array[Sprite2D] = []
var occluder_sprites: Array[Sprite2D] = []
var player_shadow_offset := Vector2.ZERO
var player_shadow_scale := Vector2.ONE
var cloaked_demon_shadow_offset := Vector2.ZERO
var cloaked_demon_shadow_scale := Vector2.ONE
var player_sprite_shadow: Sprite2D = null
var cloaked_demon_sprite_shadow: Sprite2D = null
var current_target: Sprite2D = null
var target_input_was_down := false
var player_health := 0.0
var player_death_pending := false
var player_dead := false
var player_death_timer := 0.0
var player_death_particles_started := false
var hitstop_timer := 0.0
var player_death_overlay: Sprite2D = null
var player_death_origin := Vector2.ZERO
var player_death_offset := Vector2.ZERO
var player_death_scale := Vector2.ONE
var player_death_texture: Texture2D = null
var game_over_overlay: ColorRect = null
var game_over_button: Button = null
var game_over_title_button: Button = null
var game_over_fade_timer := 0.0
var title_overlay: ColorRect = null
var title_start_button: Button = null
var title_frame_timer := 0.0
var title_screen_text: Sprite2D = null
var title_start_text: Sprite2D = null
var title_transition_active := false
var title_transition_timer := 0.0
var title_particle_layer: Node2D = null
var archetype_overlay: ColorRect = null
var archetype_hold_cover: ColorRect = null
var archetype_preview: Sprite2D = null
var archetype_name_text: Sprite2D = null
var archetype_preview_frames: Array[Texture2D] = []
var archetype_preview_palette := ""
var archetype_start_button: Button = null
var archetype_left_buttons: Array[Button] = []
var archetype_right_buttons: Array[Button] = []
var archetype_type_left_button: Button = null
var archetype_type_right_button: Button = null
var archetype_frame_timer := 0.0
var archetype_index := 0
var archetype_color_index := 0
var archetype_menu_row := 0
var archetype_transition_active := false
var archetype_transition_timer := 0.0
var archetype_fade_out := false
var archetype_arrow_anim_timer := 0.0
var archetype_arrow_anim_direction := 0
var selected_archetype := StatsComponent.AllocationProfile.BALANCED
var player_palette_name := "blue"
var player_base_idle_frames: Array[Texture2D] = []
var player_base_walk_frames: Array[Texture2D] = []
var player_base_roll_frames: Array[Texture2D] = []
var player_base_attack_frames: Array[Texture2D] = []
var player_base_attack2_frames: Array[Texture2D] = []
var player_base_attack_left_frames: Array[Texture2D] = []
var player_base_attack2_left_frames: Array[Texture2D] = []
var player_base_between_attack_texture: Texture2D = null
var player_base_after_attack2_texture: Texture2D = null
var player_base_health_fill_texture: Texture2D = null
var scene_transition_overlay: ColorRect = null
var scene_transition_timer := 0.0
var scene_transition_active := false
var loading_screen_overlay: ColorRect = null
var loading_screen_text: Sprite2D = null
var loading_screen_active := false
var loading_screen_fading := false
var loading_screen_timer := 0.0
var gold := 0
var interact_input_was_down := false
var chest_unlocked := false
var chest_claimed := false
var chest_collect_flash_timer := 0.0
var chest_evaporated := false
var door_active := false
var entrance_open := false
var dungeon_graph := DungeonGraph.new()
var current_room_id: StringName = DungeonGraph.START_ROOM_ID
var current_room_depth := 0
var current_room_display_number := 1
var current_room_type: StringName = DungeonGraph.ROOM_START
var room_transition_locked := false
var chest_normal_texture: Texture2D = null
var chest_gray_texture: Texture2D = null
var chest_unlock_overlay: Sprite2D = null
var chest_flash_overlay: Sprite2D = null
var interact_prompt: Sprite2D = null
var interact_prompt_base_position := Vector2.ZERO
var npc_dialogue_box: ColorRect = null
var npc_dialogue_text: Sprite2D = null
var npc_dialogue_button: Sprite2D = null
var npc_dialogue_button_shadow: Sprite2D = null
var npc_dialogue_layer: CanvasLayer = null
var npc_dialogue_input_was_down := false
var npc_dialogue_index := 0
var npc_dialogue_messages := ["GO ON", "TRUST YOUR PATH", "THE FIRE KNOWS", "YOU ARE CLOSE"]
var room_number_indicator: Sprite2D = null
var gold_indicator: Sprite2D = null
var gold_amount_indicator: Sprite2D = null
var gold_animation_frames: Array[Texture2D] = []
var gold_animation_timer := 0.0
var button_hud_sprites: Array[Sprite2D] = []
var target_health_text: Sprite2D = null
var player_health_text: Sprite2D = null
var player_start_position := Vector2.ZERO
var chest_start_position := Vector2.ZERO
var cloaked_demon_start_position := Vector2.ZERO
var target_health_damage_fill: Sprite2D = null
var target_health_bar_size := Vector2.ZERO
var player_health_fill_size := Vector2.ZERO
var health_bar_texture_cache: Dictionary = {}
var player_health_damage_fill: Sprite2D = null
var player_display_health := 0.0
var player_damage_fill_hold_timer := 0.0
var rest_fire_frames: Array[Texture2D] = []
var cloaked_demon_idle_frames: Array[Texture2D] = []
var cloaked_demon_walk_frames: Array[Texture2D] = []
var cloaked_demon_animation_timer := 0.0
var cloaked_demon_animation_frame := 0
var cloaked_demon_wander_timer := 0.0
var cloaked_demon_wander_origin := Vector2.ZERO
var cloaked_demon_patrol_direction := -1.0
var cloaked_demon_patrol_paused := false
var cloaked_demon_patrol_pause_timer := 0.0
var cloaked_demon_patrol_position_x := 0.0
var cloaked_demon_patrol_min_x := 0.0
var cloaked_demon_patrol_max_x := 0.0
var cloaked_demon_wander_target := Vector2.ZERO
var cloaked_demon_wander_has_target := false
var cloaked_demon_visual_bounds := Rect2(12, 10, 12, 16)
var rng := RandomNumberGenerator.new()
var sprite_frame_library := SpriteFrameLibrary.new()
var combat_tuning := CombatTuning.new()
var player_tuning := PlayerTuning.new()
var slime_tuning := SlimeTuning.new()
var effects_tuning := EffectsTuning.new()
var last_damage_was_critical := false
